### ISSUE TITLE
Multiple bets at once can result in people betting more points than they have. 

### ISSUE THREAD

**Issue by impbns** [Vinlock/IMP-Bot#4]
(Example: I have 50,000 points, 2 people bet me for 50,000 points - 100,000 points are bet) - This can involve 3 people, or 1 person betting the same other person twice.

**Comment by dakdevs** [comment]
This will take a bit of work. I will need to rework the !pvd system into objects or a database to prevent this. Since there is no visibility between the !pvd matches at all, at the moment.

**Comment by dakdevs** [comment]
I could just add the users to a list until the bet ends. If I did that it may allow that sort of visibility.

**Comment by dakdevs** [comment]
I added users to a list and remove them when the bet is done/over/cancelled. Let's see if this works.
